name: easy_mask_example
version: 0.0.1
publish_to: none

description: TextInputMask ready to be used just passing a String patterned parameter.
homepage: https://github.com/danilocoppi/flutter-textfiled-mask

environment:
  sdk: ">=3.11.4 <4.0.0"

dependencies:
  easy_mask:
      path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true


